..

diff --git a/bin/packman-prepare-build-env b/bin/packman-prepare-build-env
--- a/bin/packman-prepare-build-env
+++ b/bin/packman-prepare-build-env
@@ -16,17 +16,21 @@
 
 #set -o nounset                              # Treat unset variables as an error
 DIRNAME=`dirname $0`
-NEEDED_FILES="/home/packman/etc/packman.rc $DIRNAME/packman-functions.rc $DIRNAME/colors.rc"
+if [ ! -r /home/packman/etc/packman.rc ];then
+	echo "Missing /home/packman/etc/packman.rc. Something is wrong with your ENV. Exiting."
+	exit 1
+fi
+. /home/packman/etc/packman.rc
+NEEDED_FILES="$PACKMAN_HOME/etc/package.rc $DIRNAME/packman-functions.rc"
 for NEEDED_FILE in $NEEDED_FILES;do
         if [ ! -r $NEEDED_FILE ];then
                 echo "Missing $NEEDED_FILE. Something is wrong with your ENV. Exiting."
-                exit 1
+                exit 2
         fi
         . $NEEDED_FILE
 done
 
 
-. /home/packman/etc/packman.rc
 . $PACKMAN_HOME/etc/package.rc
 add_github_com_to_known_hosts
 git clone $PACKMAN_BASE_GIT_REPO/$PACKMAN_SPACE 
