.

diff --git a/bin/packman-build-npm b/bin/packman-build-npm
--- a/bin/packman-build-npm
+++ b/bin/packman-build-npm
@@ -89,6 +89,8 @@ if [ -n "$NEW_SPEC_GENERATED" ];then
 	/usr/bin/packman-gen-npm-deps.php package.json ${DEPS_FILE}
 else
 	CURRENT_VERSION=`npm show $PACKAGE_NAME version`
+	# because stupidly, npm version fails it asked to set the same version as what already exists
+	npm version ${PACKAGE_VERSION} 2>/dev/null||true
 set -x
 	if [ "$CURRENT_VERSION" = ${PACKAGE_VERSION} ];then
 		NEW_PACKAGE_VERSION=`npm version patch |sed 's@^v@@g'`
@@ -104,9 +106,7 @@ set -x
 		new_event_api $EVENT_INFO $JOB_ID "${PACKAGE_NAME} version ${PACKAGE_VERSION} already exists in the NPM registry, updated version to $NEW_PACKAGE_VERSION"
 		PACKAGE_VERSION=$NEW_PACKAGE_VERSION
 set +x
-	else
-		# because stupidly, npm version fails it asked to set the same version as what already exists
-		npm version ${PACKAGE_VERSION} 2>/dev/null||true
+	#else
 	fi
 	# if the code uses bower in scripts, do not show it as unused.
 	if grep "bower \|#!.*bower" * -r -q ;then 
